FROM i3c/base/ubuntu18

RUN apt-get install -y git-core build-essential python python-pip 
	
RUN git clone https://github.com/slydetector/simply-nzedb.git nzedb \
	&& cd nzedb \
	&& pip install virtualenv \
	&& make venv `# Create a python virtualenv for docker-compose` \
 	&& cp etc/simply_nzedb.conf.example etc/simply_nzedb.conf `# Create a copy of the *single* config file` \
	&& bin/setup_data_dir	

COPY mariadb/my.cnf /nzedb/data/etc_mysql_conf.d/local.cnf
RUN chmod 640 /nzedb/data/etc_mysql_conf.d/local.cnf

#let's install dind with some nice oneliner ...
RUN		apt-get update && \
		apt-get -y install apt-transport-https \
     	ca-certificates \
     	curl \
     	gnupg2 \
     	software-properties-common && \
		curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
		add-apt-repository \
   		"deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
  	 	$(lsb_release -cs) \
   		stable" && \
		apt-get update && \
		apt-get -y install docker-ce
		
COPY mariadb/dockerfile /nzedb/mariadb/Dockerfile	

WORKDIR /nzedb	

COPY ./run-nzedb.sh /
RUN chmod a+x /run-nzedb.sh && ln -sfn /run-nzedb.sh /r